spring:
  datasource:
    #    url: jdbc:postgresql://76.131.177.57:5432/postgres
    #    username: baeldung
    #    password: baeldung
    url: jdbc:postgresql://nasally-righteous-dinosaur.data-1.use1.tembo.io:5432/postgres
    username: postgres
    password: FoDK1b7X4EMNxulk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: tasktrackr.notifications@gmail.com
    password: jtrbsendpfbphvsn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations: classpath:/static/, file:./src/main/resources/static/

frontend:
  url: http://localhost:4200

logging.level.root: INFO
logging.level.CS3300: INFO




